title: Yuxuan (Lake) Wang
logo: /asset/profile-pic.png
description: Data Science Master Graduate with experience in predictive modeling across finance, healthcare and consulting
show_downloads: false
theme: jekyll-theme-minimal
